version: '3.3'
services:
  portainer-ce:
    container_name: portainer
    ports:
      - 9000:9000
    privileged: false
    entrypoint:
      - /portainer
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $DOCKERPATH/portainer/data:/data
    networks:
      - internal
    restart: always
    image: portainer/portainer-ce
  watchtower:
    container_name: watchtower
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: always
    environment:
      - WATCHTOWER_POLL_INTERVAL=86400
    image: containrrr/watchtower
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    networks:
      - external
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=America/Denver
      - SUBDOMAINS=$DOMAINNAME
      - TOKEN=$DUCKDNSTOKEN
      - LOG_FILE=false #optional
    volumes:
      - $DOCKERPATH/duckdns:/config #optional
    restart: unless-stopped
networks:
  internal:
    external: true
  external:
    external: true